### ISSUE TITLE
`watson edit` should detect invalid start/stop time

### ISSUE THREAD

**Issue by NateEag** [TailorDev/Watson#194]
Yesterday I ran `watson edit` and inadvertantly swapped the start and stop times.

It took me a little while to figure out why my report was off by a few hours, but once I found the negative time delta, it was obvious, and I fixed it.

It seems to me that `watson edit` should reject the change if start time is after stop time in the newly-edited frame.

**Comment by willdurand** [comment]
It happens to me once or twice too, but you can eventually figure it out. I am not sure but I'd say it would a lot of work to provide error detection for little gain since: 1. you don't run `edit` so often, and 2. `edit` is a "destructive" command that requires the users to be careful 😉

**Comment by NateEag** [comment]
I did a quick hack in my local installation just to see if it worked, and while it's clearly not how to exit from a Click app, adding this before [line 749 of cli.py in v1.5.2](https://github.com/TailorDev/Watson/blob/1.5.2/watson/cli.py#L749) seems to prevent the write fine:

```python
    delta = stop - start
    if delta.total_seconds() < 0:
        raise Exception('Start time is after stop time! Rejecting! ' + str(delta)
```

If it were fixed to exit properly, would you accept a PR?

**Comment by k4nar** [comment]
I think it's a great idea yes :+1: . `edit` is destructive, but if we can ward the user we should do it.

**Comment by NateEag** [comment]
I haven't found the time to look at this yet, but a note on something I just discovered:

`watson edit` will output the message "Error: The edited frame must contain the project, start and stop keys." if you remove the stop key during an edit session.

Find the source of that message and adjust the code I proposed to generate the error message the same way (and to run in the same place, since validations belong together).

**Comment by braincow** [comment]
In my pull request I implemented similar feature and a test for it. I could take a whack at this this weekend if thats ok?

**Comment by braincow** [comment]
My proposal [branch](https://github.com/braincow/Watson/tree/edit_date_validation). If this fits I can make a formal pull request out of it.

I also made the edit function a little bit more user friendly in any error case too and thus editor is presented again unless user cuts out with ctrl+c.

**Comment by k4nar** [comment]
I only took a glimpse, but it would make a great PR. Too bad we still don't have unit tests for the CLI :( .

**Comment by davidag** [comment]
This issue seems to have been fixed in #203 :tada:
